---
apiVersion: v1
kind: Service
metadata:
  name: statistics
spec:
  type: LoadBalancer
  selector:
    app: statistics
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-app-deployment
  labels:
    app: statistics-app
spec:
  selector:
    matchLabels:
      app: statistics
  replicas: 2
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - name: statistics
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/statistics/stat:version1