---
apiVersion: v1
kind: Service
metadata:
  name: statistics
spec:
  type: LoadBalancer
  selector:
    app: statistics # Selecting PODS with whose labels
  ports:
    - port: 8081 # port on Load Balancer
      targetPort: 8081 #port on Pod
      name: statistics-app-listener
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-app-deployment
  labels:
    app: statistics
spec:
  selector:
    matchLabels:
      app: statistics
  replicas: 1
  template:
    metadata:
      labels:
        app: statistics # Service looks for those PODS Labels
    spec:
      containers:
        - name: statistics
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/statistics/stat:version1