server:
  port: 8081

spring:
  datasource:
#    username: postgres
#    password: postgres1992
    url: ${STATISTICS_URL}
    username: ${DB_USER}
    password: ${DB_USER_PASS}

  flyway:
    schemas: statistics
    user: postgres
    password: postgres1992

  jpa:
    show-sql: true