server:
  port: 8081

spring:
  datasource:
    url: STATISTICS_URL
    username: DB_USER
    password: PASS

  flyway:
    schemas: statistics
    user: DB_USER
    password: PASS

  jpa:
    show-sql: true
    #    open-in-view: false

kafka:
  bootstrap-servers: KAFKA_SERVER
  consumer:
    group-id: statistics
  topic:
    send-analytics: topic-statistics