server:
  port: 8081

spring:
  datasource:
    url: ${STATISTICS_URL}
    username: ${DB_USER}
    password: ${DB_USER_PASS}

  flyway:
    schemas: statistics
    user: postgres
    password: postgres
#      enabled: false
  jpa:
    show-sql: true
#    open-in-view: false