server:
  port: 8081

spring:
  datasource:
    url: STATISTICS_URL
    username: DB_USER
    password: PASS

  flyway:
    schemas: statistics
    user: DB_USER
    password: PASS

  jpa:
    show-sql: true