CREATE TABLE main
(
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(30)                             NOT NULL,

    CONSTRAINT pk_deposit_types PRIMARY KEY (id)
);

CREATE TABLE child
(
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(30)                             NOT NULL,
    main_id             BIGINT                                  NOT NULL,

    CONSTRAINT pk_deposits_products PRIMARY KEY (id)
);

ALTER TABLE child
    ADD CONSTRAINT fk_child_on_main FOREIGN KEY (main_id) REFERENCES main (id);
