CREATE TABLE translator_statistics
(
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    main_lang          VARCHAR(30)                             NOT NULL,
    word_eng            VARCHAR(30)                             NOT NULL,
    word_rus            VARCHAR(30)                             NOT NULL,
    count               VARCHAR(30)                             NOT NULL,

    CONSTRAINT pk_translate_count PRIMARY KEY (id)
);