name: "Deploy STATISTICS-service to k8s"
run-name: ${{ github.actor }} try to deploy commit ${{ github.sha }}

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before deploy
        uses: actions/checkout@v3

      - name: setup-secrets
        env:
          STATISTICS_URL: ${{ secrets.STATISTICS_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_USER_PASS: ${{ secrets.DB_USER_PASS }}
        working-directory: ./src/main/resources
        run: |
          sed -i "s|STATISTICS_URL|STATISTICS_URL|g" application.yaml
          sed -i "s|DB_USER|$DB_USER|g" application.yaml
          sed -i "s|PASS|$DB_USER_PASS|g" application.yaml

      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/statistics/stat:version1 .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/statistics/stat:version1

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials translator-cluster --region us-central1
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" k8s-resources.yaml
          kubectl apply -f k8s-resources.yaml
          kubectl rollout restart deployment/statistics-app-deployment