name: "setup-secrets-test"
run-name: ${{ github.actor }} setup-secrets-test

on:
  push:
    branches: [ dev, prod ]

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before deploy
        uses: actions/checkout@v3
      - name: test setup secrets
        env:
          DICTIONARY_URL: ${{ secrets.STATISTICS_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_USER_PASS: ${{ secrets.DB_USER_PASS }}
        working-directory: ./src/main/resources
        run: |
          ls -la
          sed -i "s|DB_USER|$DB_USER|g" application.yaml
          sed -i "s|DB_USER_PASS|$DB_USER_PASS|g" application.yaml