name: "Deploy STATISTICS-service to k8s"
run-name: ${{ github.actor }} try to deploy commit ${{ github.sha }}

on:
  push:
    branches: [ main ]

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update application.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: './src/main/resources/application.yaml'
          propertyPath: 'spring.datasource.url'
          value: TEST
          updateFile: true
          commitChange: false
      - name: Save application.yaml artifact
        run: mv ./src/main/resources/application.yaml ${{ runner.workspace }}/application.yaml

  test-setup-secrets:
    needs: [ setup-secrets ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test setup secrets
        working-directory: ./src/main/resources
        run: |
          cp ${{ needs.setup-secrets.outputs.workspace }}/application.yaml ./src/main/resources/application.yaml
          ls -la
          grep -m 1 "url" application.yaml
