name: "Deploy STATISTICS-service to k8s"
run-name: ${{ github.actor }} try to deploy commit ${{ github.sha }}

on:
  push:
    branches: [ main ]

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update application.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: './src/main/resources/application.yaml'
          propertyPath: 'spring.datasource.url'
          value: TEST
          updateFile: true
          commitChange: false

#    steps:
#      - uses: actions/checkout@v3
#      - name: setup secrets
#        env:
#          DICTIONARY_URL: ${{ secrets.STATISTICS_URL }}
#          DB_USER: ${{ secrets.DB_USER }}
#          DB_USER_PASS: ${{ secrets.DB_USER_PASS }}
#        working-directory: ./src/main/resources
#        run: |
#          ls -la
#          sed -i "s|DICTIONARY_URL|$DICTIONARY_URL|g" application.yaml
#          sed -i "s|DB_USER|$DB_USER|g" application.yaml
#          sed -i "s|DB_USER_PASS|$DB_USER_PASS|g" application.yaml

  test-setup-secrets:
    needs: [ setup-secrets ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test setup secrets
        working-directory: ./src/main/resources
        run: |
          ls -la
          grep -m 1 "url" application.yaml
